package pojo;
// Generated May 15, 2016 5:02:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CarFeatures generated by hbm2java
 */
@Entity
@Table(name="car_features"
    ,catalog="zooba_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class CarFeatures  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<ModelFeaturesValues> modelFeaturesValueses = new HashSet<ModelFeaturesValues>(0);

    public CarFeatures() {
    }

	
    public CarFeatures(String name) {
        this.name = name;
    }
    public CarFeatures(String name, Set<ModelFeaturesValues> modelFeaturesValueses) {
       this.name = name;
       this.modelFeaturesValueses = modelFeaturesValueses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="carFeatures")
    public Set<ModelFeaturesValues> getModelFeaturesValueses() {
        return this.modelFeaturesValueses;
    }
    
    public void setModelFeaturesValueses(Set<ModelFeaturesValues> modelFeaturesValueses) {
        this.modelFeaturesValueses = modelFeaturesValueses;
    }




}


