package pojo;
// Generated May 15, 2016 5:02:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Days generated by hbm2java
 */
@Entity
@Table(name="days"
    ,catalog="zooba_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Days  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<ServiceProviderCalendar> serviceProviderCalendars = new HashSet<ServiceProviderCalendar>(0);

    public Days() {
    }

	
    public Days(String name) {
        this.name = name;
    }
    public Days(String name, Set<ServiceProviderCalendar> serviceProviderCalendars) {
       this.name = name;
       this.serviceProviderCalendars = serviceProviderCalendars;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false, length=12)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="days")
    public Set<ServiceProviderCalendar> getServiceProviderCalendars() {
        return this.serviceProviderCalendars;
    }
    
    public void setServiceProviderCalendars(Set<ServiceProviderCalendar> serviceProviderCalendars) {
        this.serviceProviderCalendars = serviceProviderCalendars;
    }




}


