package pojo;
// Generated May 23, 2016 7:59:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Make generated by hbm2java
 */
@Entity
@Table(name="make"
    ,catalog="zooba_db"
    , uniqueConstraints = {@UniqueConstraint(columnNames="name"), @UniqueConstraint(columnNames="nice_name")} 
)
public class Make  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String niceName;
     private String image;
     private Set serviceProviders = new HashSet(0);
     private Set models = new HashSet(0);

    public Make() {
    }

	
    public Make(String name, String niceName) {
        this.name = name;
        this.niceName = niceName;
    }
    public Make(String name, String niceName, String image, Set serviceProviders, Set models) {
       this.name = name;
       this.niceName = niceName;
       this.image = image;
       this.serviceProviders = serviceProviders;
       this.models = models;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false, length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="nice_name", unique=true, nullable=false, length=150)
    public String getNiceName() {
        return this.niceName;
    }
    
    public void setNiceName(String niceName) {
        this.niceName = niceName;
    }

    
    @Column(name="image")
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="make_service_providers", catalog="zooba_db", joinColumns = { 
        @JoinColumn(name="make_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="service_provider_id", nullable=false, updatable=false) })
    public Set getServiceProviders() {
        return this.serviceProviders;
    }
    
    public void setServiceProviders(Set serviceProviders) {
        this.serviceProviders = serviceProviders;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="make")
    public Set getModels() {
        return this.models;
    }
    
    public void setModels(Set models) {
        this.models = models;
    }




}


