package pojo;
// Generated May 15, 2016 5:02:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ModelFeaturesValues generated by hbm2java
 */
@Entity
@Table(name="model_features_values"
    ,catalog="zooba_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="value") 
)
public class ModelFeaturesValues  implements java.io.Serializable {


     private Integer id;
     private CarFeatures carFeatures;
     private String value;
     private Set<VehicleModel> vehicleModels = new HashSet<VehicleModel>(0);

    public ModelFeaturesValues() {
    }

	
    public ModelFeaturesValues(CarFeatures carFeatures, String value) {
        this.carFeatures = carFeatures;
        this.value = value;
    }
    public ModelFeaturesValues(CarFeatures carFeatures, String value, Set<VehicleModel> vehicleModels) {
       this.carFeatures = carFeatures;
       this.value = value;
       this.vehicleModels = vehicleModels;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="car_features_id", nullable=false)
    public CarFeatures getCarFeatures() {
        return this.carFeatures;
    }
    
    public void setCarFeatures(CarFeatures carFeatures) {
        this.carFeatures = carFeatures;
    }

    
    @Column(name="value", unique=true, nullable=false)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="model_features", catalog="zooba_db", joinColumns = { 
        @JoinColumn(name="model_feature_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="vehicle_model_id", nullable=false, updatable=false) })
    public Set<VehicleModel> getVehicleModels() {
        return this.vehicleModels;
    }
    
    public void setVehicleModels(Set<VehicleModel> vehicleModels) {
        this.vehicleModels = vehicleModels;
    }




}


