package pojo;
// Generated May 15, 2016 5:02:58 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ServiceProviderPhone generated by hbm2java
 */
@Entity
@Table(name="service_provider_phone"
    ,catalog="zooba_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="phone") 
)
public class ServiceProviderPhone  implements java.io.Serializable {


     private Integer id;
     private ServiceProvider serviceProvider;
     private String phone;

    public ServiceProviderPhone() {
    }

    public ServiceProviderPhone(ServiceProvider serviceProvider, String phone) {
       this.serviceProvider = serviceProvider;
       this.phone = phone;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="service_provider_id", nullable=false)
    public ServiceProvider getServiceProvider() {
        return this.serviceProvider;
    }
    
    public void setServiceProvider(ServiceProvider serviceProvider) {
        this.serviceProvider = serviceProvider;
    }

    
    @Column(name="phone", unique=true, nullable=false, length=25)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }




}


