package pojo;
// Generated May 15, 2016 5:02:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * ServiceProvider generated by hbm2java
 */
@Entity
@Table(name="service_provider"
    ,catalog="zooba_db"
)
public class ServiceProvider  implements java.io.Serializable {


     private Integer id;
     private ServiceProvider serviceProvider;
     private String name;
     private String email;
     private String website;
     private Set<ServiceProviderServices> serviceProviderServiceses = new HashSet<ServiceProviderServices>(0);
     private Address address;
     private Set<ServiceProviderCalendar> serviceProviderCalendars = new HashSet<ServiceProviderCalendar>(0);
     private Set<Make> makes = new HashSet<Make>(0);
     private Set<ServiceProviderPhone> serviceProviderPhones = new HashSet<ServiceProviderPhone>(0);
     private Set<ServiceProvider> serviceProviders = new HashSet<ServiceProvider>(0);

    public ServiceProvider() {
    }

	
    public ServiceProvider(ServiceProvider serviceProvider) {
        this.serviceProvider = serviceProvider;
    }
    public ServiceProvider(ServiceProvider serviceProvider, String name, String email, String website, Set<ServiceProviderServices> serviceProviderServiceses, Address address, Set<ServiceProviderCalendar> serviceProviderCalendars, Set<Make> makes, Set<ServiceProviderPhone> serviceProviderPhones, Set<ServiceProvider> serviceProviders) {
       this.serviceProvider = serviceProvider;
       this.name = name;
       this.email = email;
       this.website = website;
       this.serviceProviderServiceses = serviceProviderServiceses;
       this.address = address;
       this.serviceProviderCalendars = serviceProviderCalendars;
       this.makes = makes;
       this.serviceProviderPhones = serviceProviderPhones;
       this.serviceProviders = serviceProviders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="service_provide_branch", nullable=false)
    public ServiceProvider getServiceProvider() {
        return this.serviceProvider;
    }
    
    public void setServiceProvider(ServiceProvider serviceProvider) {
        this.serviceProvider = serviceProvider;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", length=62)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="website")
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="serviceProvider")
    public Set<ServiceProviderServices> getServiceProviderServiceses() {
        return this.serviceProviderServiceses;
    }
    
    public void setServiceProviderServiceses(Set<ServiceProviderServices> serviceProviderServiceses) {
        this.serviceProviderServiceses = serviceProviderServiceses;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="serviceProvider")
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="serviceProvider")
    public Set<ServiceProviderCalendar> getServiceProviderCalendars() {
        return this.serviceProviderCalendars;
    }
    
    public void setServiceProviderCalendars(Set<ServiceProviderCalendar> serviceProviderCalendars) {
        this.serviceProviderCalendars = serviceProviderCalendars;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="make_service_providers", catalog="zooba_db", joinColumns = { 
        @JoinColumn(name="service_provider_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="make_id", nullable=false, updatable=false) })
    public Set<Make> getMakes() {
        return this.makes;
    }
    
    public void setMakes(Set<Make> makes) {
        this.makes = makes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="serviceProvider")
    public Set<ServiceProviderPhone> getServiceProviderPhones() {
        return this.serviceProviderPhones;
    }
    
    public void setServiceProviderPhones(Set<ServiceProviderPhone> serviceProviderPhones) {
        this.serviceProviderPhones = serviceProviderPhones;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="serviceProvider")
    public Set<ServiceProvider> getServiceProviders() {
        return this.serviceProviders;
    }
    
    public void setServiceProviders(Set<ServiceProvider> serviceProviders) {
        this.serviceProviders = serviceProviders;
    }




}


