package pojo;
// Generated May 15, 2016 5:02:58 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServiceProviderServices generated by hbm2java
 */
@Entity
@Table(name="service_provider_services"
    ,catalog="zooba_db"
)
public class ServiceProviderServices  implements java.io.Serializable {


     private Integer id;
     private Service service;
     private ServiceProvider serviceProvider;
     private Date startingHour;
     private Date endingHour;

    public ServiceProviderServices() {
    }

	
    public ServiceProviderServices(Service service, ServiceProvider serviceProvider) {
        this.service = service;
        this.serviceProvider = serviceProvider;
    }
    public ServiceProviderServices(Service service, ServiceProvider serviceProvider, Date startingHour, Date endingHour) {
       this.service = service;
       this.serviceProvider = serviceProvider;
       this.startingHour = startingHour;
       this.endingHour = endingHour;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="service_id", nullable=false)
    public Service getService() {
        return this.service;
    }
    
    public void setService(Service service) {
        this.service = service;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="service_provider_id", nullable=false)
    public ServiceProvider getServiceProvider() {
        return this.serviceProvider;
    }
    
    public void setServiceProvider(ServiceProvider serviceProvider) {
        this.serviceProvider = serviceProvider;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="starting_hour", length=8)
    public Date getStartingHour() {
        return this.startingHour;
    }
    
    public void setStartingHour(Date startingHour) {
        this.startingHour = startingHour;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="ending_hour", length=8)
    public Date getEndingHour() {
        return this.endingHour;
    }
    
    public void setEndingHour(Date endingHour) {
        this.endingHour = endingHour;
    }




}


