package pojo;
// Generated May 15, 2016 5:02:58 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TrackingData generated by hbm2java
 */
@Entity
@Table(name="tracking_data"
    ,catalog="zooba_db"
)
public class TrackingData  implements java.io.Serializable {


     private Integer id;
     private Vehicle vehicle;
     private int intialOdemeter;
     private Date dateAdded;
     private Date dateModified;
     private int vehicleTrimId;
     private Set<TrackingTypes> trackingTypeses = new HashSet<TrackingTypes>(0);

    public TrackingData() {
    }

	
    public TrackingData(Vehicle vehicle, int intialOdemeter, Date dateAdded, int vehicleTrimId) {
        this.vehicle = vehicle;
        this.intialOdemeter = intialOdemeter;
        this.dateAdded = dateAdded;
        this.vehicleTrimId = vehicleTrimId;
    }
    public TrackingData(Vehicle vehicle, int intialOdemeter, Date dateAdded, Date dateModified, int vehicleTrimId, Set<TrackingTypes> trackingTypeses) {
       this.vehicle = vehicle;
       this.intialOdemeter = intialOdemeter;
       this.dateAdded = dateAdded;
       this.dateModified = dateModified;
       this.vehicleTrimId = vehicleTrimId;
       this.trackingTypeses = trackingTypeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehicle_id", nullable=false)
    public Vehicle getVehicle() {
        return this.vehicle;
    }
    
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }

    
    @Column(name="intial_odemeter", nullable=false)
    public int getIntialOdemeter() {
        return this.intialOdemeter;
    }
    
    public void setIntialOdemeter(int intialOdemeter) {
        this.intialOdemeter = intialOdemeter;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_added", nullable=false, length=10)
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_modified", length=10)
    public Date getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }

    
    @Column(name="vehicle_trim_id", nullable=false)
    public int getVehicleTrimId() {
        return this.vehicleTrimId;
    }
    
    public void setVehicleTrimId(int vehicleTrimId) {
        this.vehicleTrimId = vehicleTrimId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="trackingData")
    public Set<TrackingTypes> getTrackingTypeses() {
        return this.trackingTypeses;
    }
    
    public void setTrackingTypeses(Set<TrackingTypes> trackingTypeses) {
        this.trackingTypeses = trackingTypeses;
    }




}


