package pojo;
// Generated May 23, 2016 7:59:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TrackingData generated by hbm2java
 */
@Entity
@Table(name="tracking_data"
    ,catalog="zooba_db"
)
public class TrackingData  implements java.io.Serializable {


     private Integer id;
     private Type type;
     private Vehicle vehicle;
     private int intialOdemeter;
     private Date dateAdded;
     private Date dateModified;
     private String value;

    public TrackingData() {
    }

	
    public TrackingData(Type type, Vehicle vehicle, int intialOdemeter, Date dateAdded) {
        this.type = type;
        this.vehicle = vehicle;
        this.intialOdemeter = intialOdemeter;
        this.dateAdded = dateAdded;
    }
    public TrackingData(Type type, Vehicle vehicle, int intialOdemeter, Date dateAdded, Date dateModified, String value) {
       this.type = type;
       this.vehicle = vehicle;
       this.intialOdemeter = intialOdemeter;
       this.dateAdded = dateAdded;
       this.dateModified = dateModified;
       this.value = value;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_id", nullable=false)
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehicle_id", nullable=false)
    public Vehicle getVehicle() {
        return this.vehicle;
    }
    
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }

    
    @Column(name="intial_odemeter", nullable=false)
    public int getIntialOdemeter() {
        return this.intialOdemeter;
    }
    
    public void setIntialOdemeter(int intialOdemeter) {
        this.intialOdemeter = intialOdemeter;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_added", nullable=false, length=10)
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_modified", length=10)
    public Date getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }

    
    @Column(name="value")
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


