package pojo;
// Generated May 23, 2016 7:59:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Trim generated by hbm2java
 */
@Entity
@Table(name="trim"
    ,catalog="zooba_db"
)
public class Trim  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set vehicleModels = new HashSet(0);

    public Trim() {
    }

	
    public Trim(String name) {
        this.name = name;
    }
    public Trim(String name, Set vehicleModels) {
       this.name = name;
       this.vehicleModels = vehicleModels;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="trim")
    public Set getVehicleModels() {
        return this.vehicleModels;
    }
    
    public void setVehicleModels(Set vehicleModels) {
        this.vehicleModels = vehicleModels;
    }




}


