package pojo;
// Generated May 23, 2016 7:59:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Trips generated by hbm2java
 */
@Entity
@Table(name="trips"
    ,catalog="zooba_db"
)
public class Trips  implements java.io.Serializable {


     private Integer id;
     private Vehicle vehicle;
     private String image;
     private int coveredMilage;
     private int intialOdemeter;
     private Set coordinateses = new HashSet(0);

    public Trips() {
    }

	
    public Trips(Vehicle vehicle, int coveredMilage, int intialOdemeter) {
        this.vehicle = vehicle;
        this.coveredMilage = coveredMilage;
        this.intialOdemeter = intialOdemeter;
    }
    public Trips(Vehicle vehicle, String image, int coveredMilage, int intialOdemeter, Set coordinateses) {
       this.vehicle = vehicle;
       this.image = image;
       this.coveredMilage = coveredMilage;
       this.intialOdemeter = intialOdemeter;
       this.coordinateses = coordinateses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehicle_id", nullable=false)
    public Vehicle getVehicle() {
        return this.vehicle;
    }
    
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }

    
    @Column(name="image")
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    
    @Column(name="covered_milage", nullable=false)
    public int getCoveredMilage() {
        return this.coveredMilage;
    }
    
    public void setCoveredMilage(int coveredMilage) {
        this.coveredMilage = coveredMilage;
    }

    
    @Column(name="intial_odemeter", nullable=false)
    public int getIntialOdemeter() {
        return this.intialOdemeter;
    }
    
    public void setIntialOdemeter(int intialOdemeter) {
        this.intialOdemeter = intialOdemeter;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="trips")
    public Set getCoordinateses() {
        return this.coordinateses;
    }
    
    public void setCoordinateses(Set coordinateses) {
        this.coordinateses = coordinateses;
    }




}


