package pojo;
// Generated May 23, 2016 7:59:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name="type"
    ,catalog="zooba_db"
)
public class Type  implements java.io.Serializable {


     private Integer id;
     private MeasuringUnit measuringUnit;
     private Service service;
     private String name;
     private Set trackingDatas = new HashSet(0);

    public Type() {
    }

	
    public Type(MeasuringUnit measuringUnit, Service service, String name) {
        this.measuringUnit = measuringUnit;
        this.service = service;
        this.name = name;
    }
    public Type(MeasuringUnit measuringUnit, Service service, String name, Set trackingDatas) {
       this.measuringUnit = measuringUnit;
       this.service = service;
       this.name = name;
       this.trackingDatas = trackingDatas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="measuring_unit_id", nullable=false)
    public MeasuringUnit getMeasuringUnit() {
        return this.measuringUnit;
    }
    
    public void setMeasuringUnit(MeasuringUnit measuringUnit) {
        this.measuringUnit = measuringUnit;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="service_id", nullable=false)
    public Service getService() {
        return this.service;
    }
    
    public void setService(Service service) {
        this.service = service;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="type")
    public Set getTrackingDatas() {
        return this.trackingDatas;
    }
    
    public void setTrackingDatas(Set trackingDatas) {
        this.trackingDatas = trackingDatas;
    }




}


