package pojo;
// Generated May 15, 2016 5:02:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VehicleModel generated by hbm2java
 */
@Entity
@Table(name="vehicle_model"
    ,catalog="zooba_db"
)
public class VehicleModel  implements java.io.Serializable {


     private Integer id;
     private Model model;
     private Trim trim;
     private Year year;
     private Set<ModelFeaturesValues> modelFeaturesValueses = new HashSet<ModelFeaturesValues>(0);
     private Set<Vehicle> vehicles = new HashSet<Vehicle>(0);

    public VehicleModel() {
    }

	
    public VehicleModel(Model model, Trim trim, Year year) {
        this.model = model;
        this.trim = trim;
        this.year = year;
    }
    public VehicleModel(Model model, Trim trim, Year year, Set<ModelFeaturesValues> modelFeaturesValueses, Set<Vehicle> vehicles) {
       this.model = model;
       this.trim = trim;
       this.year = year;
       this.modelFeaturesValueses = modelFeaturesValueses;
       this.vehicles = vehicles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="model_id", nullable=false)
    public Model getModel() {
        return this.model;
    }
    
    public void setModel(Model model) {
        this.model = model;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="trim_id", nullable=false)
    public Trim getTrim() {
        return this.trim;
    }
    
    public void setTrim(Trim trim) {
        this.trim = trim;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="year_id", nullable=false)
    public Year getYear() {
        return this.year;
    }
    
    public void setYear(Year year) {
        this.year = year;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="model_features", catalog="zooba_db", joinColumns = { 
        @JoinColumn(name="vehicle_model_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="model_feature_id", nullable=false, updatable=false) })
    public Set<ModelFeaturesValues> getModelFeaturesValueses() {
        return this.modelFeaturesValueses;
    }
    
    public void setModelFeaturesValueses(Set<ModelFeaturesValues> modelFeaturesValueses) {
        this.modelFeaturesValueses = modelFeaturesValueses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vehicleModel")
    public Set<Vehicle> getVehicles() {
        return this.vehicles;
    }
    
    public void setVehicles(Set<Vehicle> vehicles) {
        this.vehicles = vehicles;
    }




}


