package pojo;
// Generated May 15, 2016 5:02:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Year generated by hbm2java
 */
@Entity
@Table(name="year"
    ,catalog="zooba_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Year  implements java.io.Serializable {


     private Integer id;
     private int name;
     private Set<VehicleModel> vehicleModels = new HashSet<VehicleModel>(0);

    public Year() {
    }

	
    public Year(int name) {
        this.name = name;
    }
    public Year(int name, Set<VehicleModel> vehicleModels) {
       this.name = name;
       this.vehicleModels = vehicleModels;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false)
    public int getName() {
        return this.name;
    }
    
    public void setName(int name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="year")
    public Set<VehicleModel> getVehicleModels() {
        return this.vehicleModels;
    }
    
    public void setVehicleModels(Set<VehicleModel> vehicleModels) {
        this.vehicleModels = vehicleModels;
    }




}


